Convert MAD-NG track to TBT data
pylhc/turn_by_turn pull request #21
Opened 2024-12-16 11:14 UTC by jgray-19

- Adds MAD-NG compatibility
- Requires tfs > 4.0.0

This will remain a draft while this is not merged: https://github.com/pylhc/tfs/pull/135

2025-01-06 10:02 UTC, fsoubelet commented
A few things to remember before I look at the implementation:

- Let's take the opportunity to drop Python 3.9
- Let's remember to add the module to the docs (in readers)

On another note, adding `tfs-pandas` as a dependency would require us to change the order of the `turn-by-turn` package in the req file for the dev environment on `lintrack`, as this package would then depend on our packages as well. Waiting to hear the opinion of @JoschD on this move, but I don't have an issue with it.

2025-01-06 10:15 UTC, JoschD requested changes
A writer would also be quick to be implemented, right? Might actually be a nice format for small machines.

2025-01-06 10:15 UTC, JoschD commented on turn_by_turn/madng.py
> +    LOGGER.info("Starting to read TBT data")
leftover?

2025-01-06 10:15 UTC, JoschD commented on turn_by_turn/madng.py
> +    LOGGER.info("Starting to read TBT data from dataframe")
for consitency: debug for reading, info for writing (it seems)

2025-01-06 10:15 UTC, JoschD commented on turn_by_turn/madng.py
> +        ), "The number of BPMs is not consistent for all particles/turns. Simulation may have lost particles."
In ESRF reader we do a similar check, but raise `ValueError`

2025-01-06 10:15 UTC, JoschD commented on turn_by_turn/madng.py
> +        subdf = df.loc[particle_id + 1]  # Particle ID starts from 1 (not 0)
`df_particle` ?

2025-01-06 10:15 UTC, JoschD commented on turn_by_turn/madng.py
> +    LOGGER.info("Finished reading TBT data")
debug

2025-01-06 10:15 UTC, JoschD commented on turn_by_turn/madng.py
> +    return TbtData(matrices=matrices, bunch_ids=list(range(npart)), nturns=nturns)
I'd probably go with the same as particle IDs. So `range(1, npart+1)` [one could also use that in the loop above instead of particle_id + 1]

2025-01-06 10:15 UTC, JoschD commented on turn_by_turn/madng.py
> +        LOGGER.info(f"Processing particle ID: {particle_id + 1}")
debug

2025-01-06 10:15 UTC, JoschD commented on turn_by_turn/madng.py
> +    bpms = df["name"].unique()
make column names final globals

2025-01-06 10:17 UTC, JoschD commented
> A few things to remember before I look at the implementation:
> (...)

Yes. I am fine with this. easy fix in lintrack. and good to remember the docs

2025-01-06 10:18 UTC, JoschD commented on turn_by_turn/madng.py
> +    bpms = df["name"].unique()
(by which I mean `NAME = 'name'`, `ID = 'id'` etc.

2025-01-06 10:25 UTC, JoschD commented on turn_by_turn/madng.py
> +        subdf.set_index(["eidx"], inplace=True)
why not use 'name' ? Then you can do `subdf.loc[bpms, field.lower()]` below and always be sure that bpms and your data are in the same order. Which is not ensured at the moment (as I am not sure if `unique` returns always the same order?)

2025-01-06 10:26 UTC, JoschD commented on turn_by_turn/madng.py
> +            for field in TransverseData.fieldnames()
would rename `field` to `plane` as this is  what is done here.

2025-01-06 10:34 UTC, fsoubelet requested changes
It is the new year and I am feeling nitpicky but it's because I love you 😬

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/madng.py
> +    LOGGER.info("Starting to read TBT data")
Duplicate logging statement, let's remove this one.

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/io.py
> +This module contains high-level I/O functions to read and write turn-by-turn data objects in different
Writing it on the only modified line: let's also add the new reader module in here (lower, in `TBT_MODULES` and `WRITERS`)

2025-01-06 10:34 UTC, fsoubelet commented on pyproject.toml
> +    "tfs-pandas >= 4.0.0", # for madng (potentially an optional dependency)
Writing on modified line: let's drop 3.9. Also should bump to a feature version in the `__init__.py`

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/madng.py
> +    LOGGER.info("Starting to read TBT data from dataframe")
Should go before the actual file reading.

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/madng.py
> +    nbpms = len(bpms)
I assume in MAD-NG it is also possible to observe at any element. I would rather rename these as `observation_points` and `n_obs_points` for instance.

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/madng.py
> +    df.set_index(["id"], inplace=True)
In `pandas`, using `inplace` is often times a false friend and will not do so. Let's take the safe path and go with an assignment:
```python
df = df.set_index("id")
```

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/madng.py
> +    for particle_id in range(npart):
Since MAD-NG counts from 1, let's do the same and go with `range(1, npart+1)`. We avoid potential errors of having to add 1 to `particle_id` everywhere afterwards. Could use a reminder comment too :)

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/madng.py
> +        subdf = df.loc[particle_id + 1]  # Particle ID starts from 1 (not 0)
I would be safe and use a `.copy()` here, even if it costs us time on bigger files. Pandas likes to use views and modifying the subdf will potentially (likely) modify the initial one as well.
```python
subdf = df.loc[particle_id].copy()
```

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/madng.py
> +"""
Let's remember to add this to the doc pages!

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/madng.py
> +        ), "The number of BPMs is not consistent for all particles/turns. Simulation may have lost particles."
Is this a no-go then? I don't remember if/how we handle this in other readers. Don't have an issue with erroring here, but I would prefer a check and raise. If someone has a habit of running their python with debug mode off this line would not run.

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/madng.py
> +        subdf.set_index(["eidx"], inplace=True)
Let's also avoid `inplace` here:
```python
subdf = subdf.set_index("eidx")
```

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/madng.py
> +        # Set the index to the element index, which are unique for every BPM and turn
Let's also call it "observation point" instead of BPM here.

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/madng.py
> +                # ^ Number of BPMs x Number of turns, Fortran order (So that the BPMs are the rows)
Nice!

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/madng.py
> +    # Should we also provide date? (jgray 2024)
The `TbtData` class assigns a simple "today in UTC" if it is not provided, so not to worry here ;)

2025-01-06 10:34 UTC, fsoubelet commented on turn_by_turn/sps.py
> +        pattern = re.compile(r"\.[HV]$", flags=re.IGNORECASE)
Thanks!

2025-01-06 10:34 UTC, fsoubelet commented on tests/test_madng.py
> +    return TbtData(matrices=matrix, bunch_ids=[0, 1], nturns=3)
Bit hardcore but alright.

2025-01-06 10:38 UTC, JoschD commented on turn_by_turn/madng.py
> +        subdf = df.loc[particle_id + 1]  # Particle ID starts from 1 (not 0)
but there is no modification. it's all views and reshaping of views

2025-01-06 10:42 UTC, JoschD commented on turn_by_turn/madng.py
> +    # Should we also provide date? (jgray 2024)
but the tfs file has a date and a time in the headers. I would use that one, if present

2025-01-06 10:44 UTC, fsoubelet commented on turn_by_turn/madng.py
> +        subdf = df.loc[particle_id + 1]  # Particle ID starts from 1 (not 0)
Looking at the code I would agree with you, but every time I see the gargantuan pile of issues raises in `pandas-dev/pandas` avoid messed up dataframes due to views acting in unpredictable ways, I am worried. As you guys feel.

2025-01-06 10:45 UTC, jgray-19 commented on turn_by_turn/madng.py
> +        subdf = df.loc[particle_id + 1]  # Particle ID starts from 1 (not 0)
I do change the index, but I assume that is still a view, since no data is modified?

2025-01-06 10:45 UTC, fsoubelet commented on turn_by_turn/madng.py
> +    # Should we also provide date? (jgray 2024)
Good catch, we should check for this!

2025-01-06 10:49 UTC, jgray-19 commented on turn_by_turn/madng.py
> +        ), "The number of BPMs is not consistent for all particles/turns. Simulation may have lost particles."
It's not exactly a no go. But I found it useful when I was using the code, so I could make this check optional, if someone does want to use TBT with lost particles or just have it in my own code. Would just mean nturns is dependant on the particle.

2025-01-06 11:04 UTC, jgray-19 commented on turn_by_turn/madng.py
> +        subdf.set_index(["eidx"], inplace=True)
Nice catch

2025-01-06 13:18 UTC, jgray-19 commented on turn_by_turn/madng.py
> +        subdf.set_index(["eidx"], inplace=True)
It is now quite different, what do you think?

2025-01-06 13:24 UTC, jgray-19 commented
> A writer would also be quick to be implemented, right? Might actually be a nice format for small machines.

What would the writer do? Convert the TBT file to a MAD-NG TFS tracking file?

2025-01-07 09:41 UTC, JoschD commented
> > A writer would also be quick to be implemented, right? Might actually be a nice format for small machines.
> 
> What would the writer do? Convert the TBT file to a MAD-NG TFS tracking file?

A writer takes a TbT - object and writes it out in the file format, here tfs. So just the inverse of the reader

2025-01-07 09:53 UTC, fsoubelet commented
I agree it would be nice to have, but it could be the object of another PR.

2025-01-07 10:01 UTC, JoschD commented on turn_by_turn/madng.py
> +    # It is possible to do this list using a list comprehension, but it would be less readable
remove comment

2025-01-07 10:01 UTC, JoschD commented on turn_by_turn/madng.py
> +                data=df_particle[plane.lower()]  # MAD-NG uses lower case field names
remove comment (or rename to `plane`)

2025-01-07 10:18 UTC, jgray-19 commented
I will see how difficult it is in a couple hours and get back to you.

2025-01-07 10:49 UTC, fsoubelet commented
@jgray-19 can you remember to up the version to `0.8.0` in the `__init__.py`?

2025-01-07 15:16 UTC, jgray-19 commented on turn_by_turn/madng.py
> +    return TbtData(matrices=matrices, bunch_ids=list(bunch_ids), nturns=nturns)
At the moment, it is set to None. Potentially, a datetime object could be created from the time and day, if they exist.

2025-01-07 15:33 UTC, fsoubelet commented on turn_by_turn/madng.py
> +    return TbtData(matrices=matrices, bunch_ids=list(bunch_ids), nturns=nturns)
I think some quick thing like:
```python
if getattr(tfs.headers, "date", None) is not None:
    date = datetime.strptime(tfs.headers.date, "%d/%m/%Y")
    # potentially also check for tfs.headers.time
```

2025-01-07 15:37 UTC, jgray-19 commented on turn_by_turn/madng.py
> +        date = tbt_data.date
So always use the date in the tbt_data?

2025-01-07 15:50 UTC, jgray-19 commented on turn_by_turn/madng.py
> +    return TbtData(matrices=matrices, bunch_ids=list(bunch_ids), nturns=nturns)
How does it look now?

2025-01-07 16:02 UTC, fsoubelet commented on turn_by_turn/madng.py
> +    return TbtData(matrices=matrices, bunch_ids=list(bunch_ids), nturns=nturns)
Good

2025-01-07 16:08 UTC, fsoubelet approved these changes

2025-01-08 09:52 UTC, merged